version: '3'

services:
  api:
    container_name: api
    build:
      context: "./backend"  
      dockerfile: Dockerfile
      args:    
        - http_proxy
        - https_proxy
    env_file:
      - .env
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
     - api
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:    
        - http_proxy
        - https_proxy
    volumes:
      - '.:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      # - HOST_NAME=${HOST_NAME}
      - CHOKIDAR_USEPOLLING=true
    networks:
     - api

networks:
  api :
      